### ISSUE TITLE
[Feature] CSV export to S3 buckets and other cloud targets

### ISSUE THREAD

**Issue by Chandra-afs** [kubecost/features-bugs#1]
### Problem Statement

Problem: Kubecost data needs to be integrated with BI and other custom FinOps tools . The following solution would help achieve this.

Please refer to the open cost implementation of CSV export to S3 bucket and other cloud targets. This really helps to integrate with existing BI and FinOps tools.
https://www.opencost.io/docs/integrations/csv-export

By doing this you can also provide/enable the current API based CSV export of cost data to include dates. Currently json export have dates. csv export is simple and nice, but dates on them would make it more usable.

### Solution Description

Please refer to the open cost implementation of CSV export to S3 bucket and other cloud targets. This really helps to integrate with existing BI and FinOps tools.
https://www.opencost.io/docs/integrations/csv-export

By doing this you can also provide/enable the current API based CSV export of cost data to include dates. Currently json export have dates. csv export is simple and nice, but dates on them would make it more usable.

### Alternatives

"Kubecost does provide access to our APIs which power all the data that you see in our UI. You can also opt to download any reports you see in the UI as a .csv. [Here is a blog](https://blog.kubecost.com/blog/integrate-kubecost-with-datadog/) we published on how users can intregrate Kubecost Data into a Datadog Dashboard."

The blog does not match with what is being requested. Blog is in particular to data log integration. The ask is an export option for the data, so we can integrate any custom solution and not to a particular tool. The open cost option of exporting the data to a bucket or storage for example is more generic and any tooling can consume it. We do not use data dog. Also sub ask in this request is adding date field to csv file that is exported out for kubecost, which does not have a date.

### Troubleshooting

- [X] I have read and followed the [issue guidelines](ISSUE_GUIDELINES.md) and this is a feature request only for the Kubecost application.
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by Chandra-afs** [comment]
@chipzoller I transitioned the feature request here.

**Comment by dwbrown2** [comment]
Thanks for sharing this request @Chandra-afs! Definitely think there's more that Kubecost can do here. Any other data requirements that you would have? For example, would you be interested in hourly data or something else? What dimensions of this data would be most helpful, e.g. container?

**Comment by chipzoller** [comment]
Hello, in an effort to consolidate our bug and feature request tracking, we are deprecating using GitHub to track tickets. If this issue is still outstanding and you have not done so already, please raise a request at https://support.kubecost.com/.
