### ISSUE TITLE
Support Azure Gov Cloud Rate Card API [Feature] 

### ISSUE THREAD

**Issue by kwombach12** [kubecost/features-bugs#10]
### Problem Statement

Moving https://github.com/kubecost/cost-analyzer-helm-chart/issues/2050#issuecomment-1739714017 over from helm chart repo

### Solution Description

see above

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/features-bugs/blob/main/ISSUE_GUIDELINES.md) and this is a feature request only for the Kubecost application.
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by chipzoller** [comment]
Hello, in an effort to consolidate our bug and feature request tracking, we are deprecating using GitHub to track tickets. If this issue is still outstanding and you have not done so already, please raise a request at https://support.kubecost.com/.
