### ISSUE TITLE
[Feature] - Add ability to aggregate allocations by Provider ID

### ISSUE THREAD

**Issue by teevans** [kubecost/features-bugs#102]
### Problem Statement

Users would like the ability to aggregate by ProviderID in a multi-aggregation scenario so they can see the providerID associated with pods. 

Requested in ticket SUP-98

### Solution Description

Adding the ability to aggregate by ProviderID in the Front-end and APIs

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/features-bugs/blob/main/ISSUE_GUIDELINES.md) and this is a feature request only for the Kubecost application.
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by teevans** [comment]
Tracking internally on [ENG-2210](https://kubecost.atlassian.net/browse/ENG-2210)

[ENG-2210]: https://kubecost.atlassian.net/browse/ENG-2210?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by chipzoller** [comment]
Hello, in an effort to consolidate our bug and feature request tracking, we are deprecating using GitHub to track tickets. If this issue is still outstanding and you have not done so already, please raise a request at https://support.kubecost.com/.
