### ISSUE TITLE
Add option to "show api call" in the UI

### ISSUE THREAD

**Issue by srpomeroy** [kubecost/features-bugs#11]
**What problem are you trying to solve?**
We consume Kubecost data via API, but we build reports in the UI to quickly verify the data. Mapping the UI data to the matching API can be difficult depending on options (aggregating by labels, filtering by labels, sharing idle, etc.) especially because the UI uses a different API than the Allocation API.

**Describe the solution you'd like**
It would be helpful if there were a way to translate what I am viewing in the UI to the matching API call.

**Describe alternatives you've considered**
Trial and error matching up UI and API calls.

**How would users interact with this feature?**
Ideally, there would be an option on the allocation page to "Show me the API call."

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-20) by [Unito](https://www.unito.io)

**Comment by teevans** [comment]
I really like this idea - GCP does this well with the "Show me the REST" button on almost every page. 
Going to throw this on the 101 planning doc.

**Comment by srpomeroy** [comment]
> I really like this idea - GCP does this well with the "Show me the REST" button on almost every page. Going to throw this on the 101 planning doc.

Yes! I knew I saw it somewhere recently but couldn't remember for the life of me.
Azure does it by generating ARM templates from resources.

**Comment by srpomeroy** [comment]
@kwombach12 Should I move this over to an Idea?

**Comment by chipzoller** [comment]
I'm not Kai but we can always transfer this to features-bugs.

**Comment by kwombach12** [comment]
@srpomeroy yes, please create a corresponding Jira Idea on our Feature Requests board

**Comment by chipzoller** [comment]
Transferred to features-bugs. Please update issue with link to Jira once created.

**Comment by dwbrown2** [comment]
@nealormsbee guessing this would be technically pretty straightforward, but let us know if you any input. 

@srpomeroy would Allocation page be highest priority? Any other priorities that you have?

**Comment by nealormsbee** [comment]
Agreed on technical difficulty. This should be very simple from an engineering implementation perspective.

**Comment by srpomeroy** [comment]
[Added in Jira](https://kubecost.atlassian.net/jira/polaris/projects/KC/ideas/view/2936873?selectedIssue=KC-127)

**Comment by srpomeroy** [comment]
> @srpomeroy would Allocation page be highest priority? Any other priorities that you have?

@dwbrown2, Reports definitely (in priority order)!

1. Allocations 
2. Assets
3. Cloud Costs
4. Advanced Reports (when the APIs are GA)

I could also see value in having it in other areas like Budgets, Alerts, etc.

**Comment by chipzoller** [comment]
Hello, in an effort to consolidate our bug and feature request tracking, we are deprecating using GitHub to track tickets. If this issue is still outstanding and you have not done so already, please raise a request at https://support.kubecost.com/.
