### ISSUE TITLE
[Feature] Provide a configuration to restrict out of cluster cost dashboard

### ISSUE THREAD

**Issue by vaibhavgn** [kubecost/features-bugs#112]
### Problem Statement

Platform: Amazon EKS

One of our K8s clusters is in the Payer account. There are other clusters in other member accounts. The Cost and usage report of Payer displays the out of cluster costs for the whole organization and so does kubecost. I just want the cost for that one cluster and its related cloud components exposed and not the whole org. 

### Solution Description

I should be able to do one of the following:
1. Disable out of cluster dashboard entirely
2. Configure Kubecost to only pull and display costs only for the given cluster and its components

### Alternatives

The alternative suggested was to create Athena views to restrict the data being pulled. 

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/features-bugs/blob/main/ISSUE_GUIDELINES.md) and this is a feature request only for the Kubecost application.
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by kwombach12** [comment]
Hey @vaibhavgn this is definitely something that's on our radar -- we expect to add the ability to filter or restrict the Cloud Costs page (so that teams only see the costs relevant to them) via our RBAC controls in the next release or two.

**Comment by chipzoller** [comment]
Hello, in an effort to consolidate our bug and feature request tracking, we are deprecating using GitHub to track tickets. If this issue is still outstanding and you have not done so already, please raise a request at https://support.kubecost.com/.
