### ISSUE TITLE
[Feature] Support Kubernetes 1.30 in AWS Marketplace listing

### ISSUE THREAD

**Issue by kgochenour** [kubecost/features-bugs#115]
### Problem Statement

I would like to use KubeCost via the EKS Add-on Module. However, Kubecost does not support EKS/Kubernetes 1.30 on version 2.3.4. (Or maybe it does, but AWS says 2.3.4 only goes to 1.29)

### Solution Description

Support Kubernetes 1.30

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/ISSUE_GUIDELINES.md) and this is a feature request only for the Helm chart.
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by teevans** [comment]
Hey there! We haven't completed a full testing cycle on that version quite yet. We'll work on getting it out as soon as possible!

**Comment by chipzoller** [comment]
This specifically pertains to the AWS Marketplace listing and not the direct Helm chart. A new AWS Marketplace listing (new version) will need to be created which specifically tags 1.30 as a supported version. It's more of a technicality than anything, but without that tag it won't appear for EKS clusters of version ≥ 1.30.

**Comment by chipzoller** [comment]
Hello, we are deprecating using GitHub to track bugs and feature requests. If this issue is still outstanding and you have not done so already, please raise a request at https://support.kubecost.com/.
