### ISSUE TITLE
[Bug] Wrong CPU core count for Alibaba Serverless Node

### ISSUE THREAD

**Issue by qixiangyang** [kubecost/features-bugs#117]
### Kubecost Version

2.3.3

### Kubernetes Version

1.28.9

### Kubernetes Platform

Other (specify in description)

### Description

Cloud Provider: Alibaba Cloud

The CPU core count of Alibaba Cloud's Serverless Node is recognized as 192,000, causing the total number of CPU cores to exceed the 250-core limit of the free version, rendering Kubecost cost unusable. However, in reality, this Serverless Node is only a backup for traffic spikes and is not typically used.

<img width="1774" alt="image" src="https://github.com/user-attachments/assets/dfe056fd-7c6e-4d8d-9e69-fcb0ec539e99">

### Steps to reproduce

1. Add a Serverless node to Alibaba Cloud K8s, and then observe Kubecost's behavior. 

### Expected behavior

The CPU core count for Alibaba Cloud Serverless nodes should be recorded as 0 or a default value in Kubecost, rather than 192,000.

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/features-bugs/blob/main/ISSUE_GUIDELINES.md) and this is a bug impacting only the Kubecost application.
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by AjayTripathy** [comment]
Thanks for this submission @qixiangyang . @kwombach12 can you help track these please? It sounds like we need to add support for Alibaba Serverless nodes.

**Comment by kwombach12** [comment]
[Ticket for Internal Tracking](https://kubecost.atlassian.net/browse/KC-333)

**Comment by chipzoller** [comment]
Hello, we are deprecating using GitHub to track bugs and feature requests. If this issue is still outstanding and you have not done so already, please raise a request at https://support.kubecost.com/.
