### ISSUE TITLE
EKS optimized: Account "__undefined__"

### ISSUE THREAD

**Issue by user24924** [kubecost/features-bugs#122]
Hello!

We recently started using EKS optimized kubecost on our clusters, and are facing an issue where account value is displayed as `__undefined__`. Including a screenshot of the UI below (this is from a node under assets).

<img width="1655" alt="account-name-undefined" src="https://github.com/user-attachments/assets/6fd8db1e-082c-43f4-9920-7c6b5bcb77f6">

  
Checking the `/model/assets?window=1d` API, we see the same thing, example pvc included below

```
      "AWS/__undefined__/Storage/cluster-one/Disk/Kubernetes/vol-*/pvc-*": {
        "type": "Disk",
        "properties": {
          "category": "Storage",
          "provider": "AWS",
          "account": "__undefined__",
          "service": "Kubernetes",
          "cluster": "cluster-one",
          "name": "pvc-*",
          "providerID": "vol-*"
        },
        "labels": {},
        "window": {
          "start": "2024-09-24T07:00:00Z",
          "end": "2024-09-24T08:00:00Z"
        },
        "start": "2024-09-24T07:00:00Z",
        "end": "2024-09-24T07:50:00Z",
        "minutes": 50.000000,
        "byteHours": 28633115306.666668,
        "bytes": 34359738368.000000,
        "byteHoursUsed": 0.000000,
        "byteUsageMax": 0.000000,
        "breakdown": {
          "idle": 1,
          "other": 0,
          "system": 0,
          "user": 0
        },
        "adjustment": 0.000000,
        "totalCost": 0.004018,
        "storageClass": "gp3",
        "volumeName": "pvc-*",
        "claimName": "kubecost-cost-analyzer",
        "claimNamespace": ""
      },
```

The only change(s) we have made to the default helm configs, is to override the cluster name (not id), and add an account mapping.

Modified configs are as below -
```
kubecostProductConfigs:
  clusterName: custom-name
  cloudAccountMapping:
      12345: AccountName
```

Apart from this issue, other functionality (including cloud costs, spot feed etc.) is working fine. Any help/pointers on what could be causing this, and how can we fix it, would be greatly appreciated.

**Comment by mittal-ishaan** [comment]
Hi,
Thanks for reporting this issue. 
I was able to reproduce this issue at my end in both EKS optimised and free version even without the helm values you have provided. I will be looking into this further to check what is causing this issue. 
One thing to note here is that:. In not the free version, this issue can only be seen in aws cloud provider
CC @jessegoodier

**Comment by mittal-ishaan** [comment]
Hey @user24924 
We are still digging into the problem and will update here once we have more clarity on the exact issue and resolution about it.

**Comment by mittal-ishaan** [comment]
Hi @user24924 
Did some digging into the issue, seems like we are not able to get the account Id for aws provider. we are trying to resolve this, and will get this fixed asap. But just to unblock you here I would suggest that you set your accountID  in the [helm values](https://github.com/kubecost/cost-analyzer-helm-chart/blob/31ce9c2172849d4d042eecf7b7d920f6165d0864/cost-analyzer/values.yaml#L3376) specifically changing the account property for assets.
cc @jessegoodier

**Comment by user24924** [comment]
@mittal-ishaan Thanks for the help, setting that property does fix this issue. I seem to have completely missed that property earlier!

**Comment by chipzoller** [comment]
Hello, we are deprecating using GitHub to track bugs and feature requests. If this issue is still outstanding and you have not done so already, please raise a request at https://support.kubecost.com/.
