### ISSUE TITLE
[Bug] Allocations API for CSV output returns a non-array result for Window schema

### ISSUE THREAD

**Issue by patcadelina** [kubecost/features-bugs#123]
### Kubecost Version

2.0.2

### Kubernetes Version

1.28.10

### Kubernetes Platform

Other (specify in description)

### Description

Kubernetes Platform: kOps on EC2 (AWS)

Instead of an easily parseable array, a text transform is first required to replace the closing parenthesis ")" with a square bracket "]".

```
Name,CPU,GPU,RAM,PV,Network,LoadBalancer,External,Shared,Efficiency,Total,Window
namespace/appID,0.076,0.000,0.009,0.000,0.000,0.000,0.000,0.000,0.630,0.085,"[2024-09-17T00:00:00+0000, 2024-09-18T00:00:00+0000)"
```

### Steps to reproduce

1. Run `curl` against the Allocation API: curl "http://localhost:9090/model/allocation/summary?format=csv&aggregate=namespace,label:app&window=2024-09-17T00:00:00Z,2024-09-18T00:00:00Z" --output 2024-09-17.csv
2. View the generated CSV

### Expected behavior

The closing parenthesis ")" should have been a square bracket "]".

```
Name,CPU,GPU,RAM,PV,Network,LoadBalancer,External,Shared,Efficiency,Total,Window
namespace/appID,0.076,0.000,0.009,0.000,0.000,0.000,0.000,0.000,0.630,0.085,"[2024-09-17T00:00:00+0000, 2024-09-18T00:00:00+0000]"
```

### Impact

There is an additional complexity in integrating Kubecost data in Glue/Quicksight.

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/features-bugs/blob/main/ISSUE_GUIDELINES.md) and this is a bug impacting only the Kubecost application.
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by nik-kc** [comment]
Hi @patcadelina, the opening bracket and closing parenthesis are intentional behavior. The window string isn't intended to be an array, but mathematical notation for inclusive-start and exclusive-end.

**Comment by patcadelina** [comment]
Hi @nik-kc, thanks for the clarification.
