### ISSUE TITLE
[Question] Why does a 4-CPU singlenode cluster with "100$/CPU" have 470$ of costs?

### ISSUE THREAD

**Issue by kastl-ars** [kubecost/features-bugs#125]
Hi all,

I am evaluating kubecost. The idea is to only get a rough percentage of the costs per namespace.

My idea was to only have a cost per CPU and month, so I set it to `100$`. All other costs in "Settings" => "Pricing" are empty.

I am running this on a single-node k3s cluster with 4 CPUs.

My naive guess was that I would end up with 400$ of costs in total for the month.

For some reason, the CPU costs are 409,92$. And there is an additional "Shared" cost of 60$, so I end up with 470$ per month.

I would like to understand why

- the CPU costs are off (409$ instead of 400)
- there are shared costs and where they come from

I am sorry if I missed this in the documentation, but the whole custom pricing is only mentioned briefly in [Pricing source matrix](https://docs.kubecost.com/architecture/pricing-sources-matrix#custom-pricing).

Kind Regards,
Johannes

**Comment by jessegoodier** [comment]
Interesting experiment, thank you for the detail.
Could you change the idle to shared vs separate to see if it changes the shared cost total?
And are the costs in assets also off by the same amount?
any screenshots you can share would be helpful too.

**Comment by kastl-ars** [comment]
OK, I created a small vagrant setup to play around with this. One VM with 4 CPUs, k3s on top, kubecost freshly installed.

-  CPU cost is set to `100` in the helm values and `100.01073888` in the GUI.
- "Settings" => "Pricing" => "Allocate Idle resources" is not enabled
- "Settings" => "Pricing" => "Highlight unreconciled costs" is not enabled
- "Settings" => "Pricing" => "Share Tenancy Costs" is enabled
- "Settings" => "Pricing" => "Shared Overhead/Namespaces/Labels/Label Values" are all empty

## Idle costs set to "separate"

Monitor => Allocations => Edit => "Cost" with "Monthly rate" shows 1200€/Month for CPU summed up over all namespaces.

![grafik](https://github.com/user-attachments/assets/26eb09b6-df1a-418c-93b2-431f3da61f19)

There are shared costs of 258€ that come out of nowhere, as none of the namespaces has anything in the Shared column.

The CPU cost column is just plain wrong. 10$ + 5$ + 2,5$ + 0,13$ => 1200€ 

## Idle costs set to "share by cluster"

Changing "Idle costs" to `Share by cluster` changes this and the shared column has values for the three namespaces.

![grafik](https://github.com/user-attachments/assets/b72666c0-e06b-4cec-873e-b81fb4460a94)

Now the CPU column actually makes sense, as the three single numbers add up to the total.

**Comment by kastl-ars** [comment]
## Assets

In "Assets" => "Edit" I changed "Cost metric" to "Monthly rate". Chart is set to "Cost over time", "Step size" is set to "Default".

![grafik](https://github.com/user-attachments/assets/b8fe188a-f19a-42b7-83c7-52884255471b)

Disk and Network are correctly shown with 0$, Node is shown with 100$ (the labels show that it is k3s with 4vCPU and 15.6 GB of RAM.

4 vCPUs but still 100$ sounds wrong. Note that it shows 100$ and not `100.01073888` which is set as Cost per CPU (at least it is shown in the GUI).

**Comment by kastl-ars** [comment]
> Interesting experiment, thank you for the detail. Could you change the idle to shared vs separate to see if it changes the shared cost total? And are the costs in assets also off by the same amount? any screenshots you can share would be helpful too.

I hope I provided the details, if not feel free to reach out.

I'll make the vagrant setup available later today, so others can test this, too.

**Comment by kastl-ars** [comment]
Oh, one other thing:

In the Assets page when I hover my mouse over the green "Node" on the left, I get this popup:

![grafik](https://github.com/user-attachments/assets/bd3c17c2-d7c0-45c9-b2e9-2a946bb711cf)

Clicking on Node and hovering over "Node/k3s1" I got hourly costs of "99.xxxxx". I cannot reproduce it, now it shows the "0.13" from the screenshot above.

**Comment by chipzoller** [comment]
Hello, we are deprecating using GitHub to track bugs and feature requests. If this issue is still outstanding and you have not done so already, please raise a request at https://support.kubecost.com/.
