### ISSUE TITLE
[Bug] Two cluser_ids in opensource version

### ISSUE THREAD

**Issue by pallr** [kubecost/features-bugs#126]
### Kubecost Version

2.4.1

### Kubernetes Version

1.28

### Kubernetes Platform

OpenShift

### Description

We are using the opensource Kubecost and first it is installed with the default cluster-one cluster_id, when i upgraded to 2.4.1 i added a new name for the same cluster in the helm chart , the upgrade was successfull but then it thinks i am managing two clusters,  after that i added back the cluser-one cluster ID in the helm config and now the running kubecost realise it but still itt think that there is a second cluster with the changed name and it cannot be used because i receive an overlay window which sais you found an Enterprise feature. I have one and only one cluster, how can i remove the change cluster name from its config? Thanks

### Steps to reproduce

1. rename the cluster in helm chart in the opensource version 

### Expected behavior

there should be a feature in the overlay to remove one cluster

### Impact

It cannot be used 

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/features-bugs/blob/main/ISSUE_GUIDELINES.md) and this is a bug impacting only the Kubecost application.
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by chipzoller** [comment]
Hello, we are deprecating using GitHub to track bugs and feature requests. If this issue is still outstanding and you have not done so already, please raise a request at https://support.kubecost.com/.
