### ISSUE TITLE
Adding label mappings in the Savings API (Container Request Right Sizing Recommendation API (V2)) response

### ISSUE THREAD

**Issue by passionInfinite** [kubecost/features-bugs#13]
**What problem are you trying to solve?**
Currently we want the savings information based on the labels that we have for the namespace and app level, currently it has ability to filter for label that means cost-model api already knows the label mappings but doesn't return those associated labels in the Savings API response.

**Describe the solution you'd like**
If we can have those labels in the response of Savings API (**Container Request Right Sizing Recommendation API (V2)**) that will help teams to do further automation such as building grafana dashboards and more.

**Describe alternatives you've considered**
We tried using the filter approach but it is overkill and doesn't help much in the automation process and taking the data for more insights because the response doesn't have Label mappings.

**How would users interact with this feature?**
Users can use the API to fetch the labels mappings with Savings API response and then Teams can further perform grouping of those savings based on the labels and perform insights with those responses as well.

**Comment by kwombach12** [comment]
@passionInfinite This makes a lot of sense to me. Seems like a relatively quick addition we can make in a future release.

**Comment by passionInfinite** [comment]
@kwombach12 Did we included this in release 1.103.5?

**Comment by kwombach12** [comment]
@passionInfinite no, we have not worked on this enhancement just yet

**Comment by passionInfinite** [comment]
@kwombach12 Any updates on this feature?

**Comment by kwombach12** [comment]
@passionInfinite we have not started work on this just yet.

**Comment by jcharcalla** [comment]
@kwombach12 has there been any progress on this?

**Comment by kwombach12** [comment]
@jcharcalla not yet, the current release, and next release (106) have been focused on bug fixes/cleanup

**Comment by passionInfinite** [comment]
Hello Kubecost Team,

Any updates on the release of 107 with this feature? We are expecting to have this included in the upcoming release this month.

**Comment by kwombach12** [comment]
@passionInfinite We are still on track to deliver this in 107 this month!

**Comment by passionInfinite** [comment]
@kwombach12  Any updates on the v1.107 release with this feature?

**Comment by mmurph3** [comment]
@passionInfinite  this is completed and is in QA now - working on getting this in a minor release of v1.106 which we're working on cutting the first release candidate for. v1.107 has a projected release date of Nov. 1st. I should have an ETA soon on the minor release of v1.106.

**Comment by passionInfinite** [comment]
@kwombach12  I can see there is a new minor release. If we want to consume that release what shall we include in the api so that api response can have labels in the results?

**Comment by chipzoller** [comment]
Transferred to features-bugs since this is a feature for the Kubecost application stack and not the Helm chart.

**Comment by mmurph3** [comment]
@passionInfinite You need to include includeLabelsAndAnnotations=true in the response. E.g.

`$ curl -G   -d 'algorithmCPU=quantile'   -d 'qCPU=0.95'   -d 'algorithmRAM=max'   -d 'targetCPUUtilization=0.8'   -d 'targetRAMUtilization=0.8'   -d 'window=3d'   --data-urlencode 'filter=namespace:"kubecost"+container:"federator"' -d includeLabelsAndAnnotations=true  ${KUBECOST_ADDRESS}/savings/requestSizingV2 | jq`

**Important Note:** Even when you see the parameter, if there aren't any labels or annotations on the pod, the fields will also not be present since they're omitted when empty.

**Comment by chipzoller** [comment]
Hello, in an effort to consolidate our bug and feature request tracking, we are deprecating using GitHub to track tickets. If this issue is still outstanding and you have not done so already, please raise a request at https://support.kubecost.com/.
