### ISSUE TITLE
Allow Cluster Rightsizing report to only suggest from allowed instance types

### ISSUE THREAD

**Issue by srpomeroy** [kubecost/features-bugs#26]
**What problem are you trying to solve?**
My organization has a predefined list of allowed instance sizes. The cluster rightsizing savings report recommends instances sizes and families that are disallowed by my organization.

**Describe the solution you'd like**
A way to define what instances/families are allowed to be suggested. Ideally, a flexible way to define what instances are allowed or disallowed based on names, families, and potentially instance properties(generation, region, network features, GPU, etc.). A good MVP would be simple name matching for allowed/disallowed.

**Describe alternatives you've considered**
Manually picking instances my organization supports based on the specs of the instances Kubecost suggests (vpcu, gb mem, etc)

**How would users interact with this feature?**
helm, configmap, API, download from object storage, settings, etc.

**Comment by srpomeroy** [comment]
Relates to:

- https://github.com/opencost/opencost/issues/985
- https://github.com/kubecost/cost-analyzer-helm-chart/issues/1316
- https://github.com/kubecost/cost-analyzer-helm-chart/issues/1117
- https://github.com/kubecost/features-bugs/issues/31

**Comment by srpomeroy** [comment]
Can we move this to the features-bugs repo please? I don’t have enough rights to do so.

**Comment by dwbrown2** [comment]
Thanks for reporting! Are there certain patterns/motivations that your organization has? For example, filter certain chipsets, processor families, etc? Current plan is to do a deep review of cluster sizing soon after 2.0 launch.

**Comment by chipzoller** [comment]
Hello, in an effort to consolidate our bug and feature request tracking, we are deprecating using GitHub to track tickets. If this issue is still outstanding and you have not done so already, please raise a request at https://support.kubecost.com/.
