### ISSUE TITLE
Allow networks-costs listen to ipv6 address

### ISSUE THREAD

**Issue by mikheevsv** [kubecost/features-bugs#27]
### Problem Statement

network-costs-rs running as daemonset listens to ipv4 addresses only
```
/ # netstat -lntp |grep network-costs *
*tcp        0      0 0.0.0.0:3001            0.0.0.0:*               LISTEN      1/network-costs-rs
```
So Prometheus, working on ipv6 network, cannot scrape its metrics.

### Solution Description

It would be great to have an opportunity to allow listening ipv6 addresses

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/features-bugs/blob/main/ISSUE_GUIDELINES.md) and this is a feature request only for the Kubecost application.
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by jessegoodier** [comment]
@mikheevsv thanks for logging this. Do you plan on testing the nginx sidecar idea?

**Comment by mikheevsv** [comment]
Hi Jesse, yes I'm going to test it this week. 
I'll be back with the results

**Comment by AjayTripathy** [comment]
Hi @mikheevsv any updates here?

**Comment by chipzoller** [comment]
Hello, in an effort to consolidate our bug and feature request tracking, we are deprecating using GitHub to track tickets. If this issue is still outstanding and you have not done so already, please raise a request at https://support.kubecost.com/.
