### ISSUE TITLE
[Feature] Support differenly step sizes in cloud data, e.g. daily, weekly, and monthly

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/features-bugs#3]
### Problem Statement

When I look at data over long windows, e.g. quarters or years, I'd really like to view it by weeks or months. 

### Solution Description

Proposal is we add a step size to this window that support default, daily, weekly, and monthly. 

<img width="1262" alt="image" src="https://github.com/kubecost/features-bugs/assets/298359/4d393f89-afc2-4528-806d-ac148d00f404">

### Troubleshooting

- [X] I have read and followed the [issue guidelines](ISSUE_GUIDELINES.md) and this is a feature request only for the Kubecost application.
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by dwbrown2** [comment]
@kwombach12 @cliffcolvin what's best way to triage from here?

**Comment by teevans** [comment]
Jira: https://kubecost.atlassian.net/browse/SELFHOST-834

**Comment by chipzoller** [comment]
Hello, in an effort to consolidate our bug and feature request tracking, we are deprecating using GitHub to track tickets. If this issue is still outstanding and you have not done so already, please raise a request at https://support.kubecost.com/.
