### ISSUE TITLE
[Feature] Method to determine if costs have been reconciled

### ISSUE THREAD

**Issue by ribeiroh** [kubecost/features-bugs#35]
### Problem Statement

When consuming allocation data via the API, there isn't a reliable method to determine if data points have already been reconciled with the CSP or not. As a comparison, there is a feature in the Kubecost UI that highlights whether or not costs have been already reconciled (although it isn't clear how reliable that functionality is either).

### Solution Description

A simple property in each data element in the return response like `reconciled: True` would be enough. Optionally, it would also be useful to be able to submit this as a query parameter. For example, to only fetch costs that have been reconciled.

### Alternatives

- Fetch data with at least 48 hours of lag: although this should work for the happy path, it's not safe in situations when problems occurred to reconcile the data.
- Test for `*CostAdjustment` properties being different than 0: although true for most cases, there's likely a variety of scenarios where the adjustment for a reconciled cost might still be 0.

**Comment by kwombach12** [comment]
@ribeiroh This idea makes a lot of sense - we have discussed this internally and already have this enhancement in our backlog!

**Comment by chipzoller** [comment]
Do we keep this issue open if there's an internal enhancement request filed?

**Comment by kwombach12** [comment]
@chipzoller Yea, we usually leave open until the enhancement is developed.

**Comment by chipzoller** [comment]
How are we ensuring that closure of the internal issue results in closure of GitHub issues?

**Comment by kwombach12** [comment]
@chipzoller Its been an ad-hoc process where I try to close out all the GH issues we tackled at the end of the release

**Comment by teevans** [comment]
@ribeiroh - I think this makes sense, but to add that flag to each individual data point may introduce some response overhead. We've also figured out that the lift to add that in would be non-trivial. Would querying our cloud status api (/model/cloudCost/status) be able to answer the question you're looking for? IE, if the cloud status is successful and reconciliation has run, would that help you determine what's been reconciled?

**Comment by ribeiroh** [comment]
@teevans thanks for following up on this. Your alternative seems interesting, although I myself don't know enough about the reconciliation process to tell you whether or not it's good enough 😄 (I also couldn't find documentation about that API endpoint specifically).

Let's imagine the following scenario: AWS is a bit late to deliver new billing data (not uncommon). When the reconciliation process runs, I imagine it will still be completed successfully, since some CUR data exists. In this case, would I get a false positive indication? Or does the API give me a safe method to determine that day/range X has been successfully reconciled?

As long as a logical method exists to determine with certainty that a given data set has been reconciled (not necessarily per individual data points as my original request), that would be enough.

**Comment by teevans** [comment]
Hey I think I can work with that - let me get with the team and see what we can do!

**Comment by Sean-Holcomb** [comment]
Reconciliation runs up to the day before yesterday. AWS releases CUR data on about an 8 hour schedule. The delay is to ensure that we have the full day of data before reconciliation occurs. 

It would be helpful to understand what you are trying to achieve, it sounds like you are pulling the allocation out of the api into your own pipeline and you want to ensure that the data you have pulled is fully reconciled before it enters your pipeline. Is that right?

**Comment by ribeiroh** [comment]
@Sean-Holcomb close, but very precisely pointed out. We indeed want to take data out of the API and onto our pipeline, but in our case we keep _both_ reference public prices as well as the discounted ones.

What we're trying to achieve is to ensure that a price we deem as being discounted has, indeed, been gone through recon and is accurate.

Thanks everyone for your efforts!

**Comment by chipzoller** [comment]
Hello, in an effort to consolidate our bug and feature request tracking, we are deprecating using GitHub to track tickets. If this issue is still outstanding and you have not done so already, please raise a request at https://support.kubecost.com/.
