### ISSUE TITLE
[Bug] Getting 0 in ExternalCost field when performing GET request to Kubecost API

### ISSUE THREAD

**Issue by magnonta** [kubecost/features-bugs#4]
### Kubecost Helm Chart Version

v1.106.0

### Kubernetes Version

1.26.3

### Kubernetes Platform

AKS

### Description

Kubecost configured and correctly integrated with Azure with no errors reported through the UI Bug Report.
Even so, when trying to get the ExternalCost value through the API, this always returns 0.

- Kubecost version

![image](https://github.com/kubecost/cost-analyzer-helm-chart/assets/34287623/e1e0eb94-7677-495d-a5dd-eb8f8d8ee36c)

- Cloud Integration

![image](https://github.com/kubecost/cost-analyzer-helm-chart/assets/34287623/a057eed8-16cb-4094-9d79-a883b18f6be8)

- Prometheus Status

![image](https://github.com/kubecost/cost-analyzer-helm-chart/assets/34287623/c8623067-073f-4037-b3e6-6c21e35995f4)

- Through the UI the value is correctly returned.

![image](https://github.com/kubecost/cost-analyzer-helm-chart/assets/34287623/5d8199b3-6384-4ef5-84dd-4634dbb7b22d)

### Steps to reproduce

1. try making a GET request to Kubecost API: curl --location 'https://xxxx.xxx.xxx.xx.ai/kubecost/model/allocation?aggregate=namespace&externalCost=true&accumulate=true&shareIdle=weighted&reconcile=false&window=7d&shareCost=100' \
--header 'Authorization: Bearer token'

Result:

`{
    "code": 200,
    "data": [
        {
            "1": {
                "name": "1",
                "properties": {
                    "namespace": "1",
                    "namespaceLabels": {
                        "istio_injection": "enabled",
                        "kubernetes_io_metadata_name": "1",
                        "zen_security": "enabled"
                    }
                },
                "window": {
                    "start": "2023-10-03T00:00:00Z",
                    "end": "2023-10-10T00:00:00Z"
                },
                "start": "2023-10-03T00:00:00Z",
                "end": "2023-10-09T15:50:00Z",
                "minutes": 9590,
                "cpuCores": 0.06648,
                "cpuCoreRequestAverage": 0.06643,
                "cpuCoreUsageAverage": 0.01415,
                "cpuCoreHours": 10.62639,
                "cpuCost": 0.92469,
                "cpuCostAdjustment": 0,
                "cpuEfficiency": 0.21304,
                "gpuCount": 0,
                "gpuHours": 0,
                "gpuCost": 0,
                "gpuCostAdjustment": 0,
                "networkTransferBytes": 3323627386.04374,
                "networkReceiveBytes": 6739244814.07457,
                "networkCost": 0.00232,
                "networkCrossZoneCost": 0,
                "networkCrossRegionCost": 0,
                "networkInternetCost": 0.00232,
                "networkCostAdjustment": 0,
                "loadBalancerCost": 0,
                "loadBalancerCostAdjustment": 0,
                "pvBytes": 0,
                "pvByteHours": 0,
                "pvCost": 0,
                "pvs": null,
                "pvCostAdjustment": 0,
                "ramBytes": 762101360.72892,
                "ramByteRequestAverage": 749403818.31074,
                "ramByteUsageAverage": 465442891.87187,
                "ramByteHours": 121809200823.17249,
                "ramCost": 0.7994,
                "ramCostAdjustment": 0,
                "ramEfficiency": 0.62108,
                "externalCost": 0,
                "sharedCost": 0.03852,
                "totalCost": 1.76493,
                "totalEfficiency": 0.40224,
                "proportionalAssetResourceCosts": {},
                "lbAllocations": null,
                "sharedCostBreakdown": {}
            }
        }
    ]
}`

### Expected behavior

Get the correct value from ExternalCost.

### Screenshots

![image](https://github.com/kubecost/cost-analyzer-helm-chart/assets/34287623/89698791-7ef6-461b-883d-afed9819341f)
![image](https://github.com/kubecost/cost-analyzer-helm-chart/assets/34287623/4b1500e3-88be-4342-a5f8-1ad755fd0b43)

### Slack discussion

#5155

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/ISSUE_GUIDELINES.md) and this is a bug impacting only the Helm chart.
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by chipzoller** [comment]
This seems like it's not related to the Helm chart but is an application-specific issue. We have a new repository set up [here](https://github.com/kubecost/features-bugs) to handle features and bugs which are with the Kubecost app stack.

**Comment by chipzoller** [comment]
Transferred

**Comment by teevans** [comment]
Jira: https://kubecost.atlassian.net/browse/SELFHOST-833

**Comment by chipzoller** [comment]
Hello, in an effort to consolidate our bug and feature request tracking, we are deprecating using GitHub to track tickets. If this issue is still outstanding and you have not done so already, please raise a request at https://support.kubecost.com/.
