### ISSUE TITLE
[Feature] Method to determine if costs have been reconciled through the API

### ISSUE THREAD

**Issue by ribeiroh** [kubecost/features-bugs#43]
### Problem Statement

When consuming allocation data via the API, there isn't a reliable method to determine if data points have already been reconciled with the CSP or not. As a comparison, there is a feature in the Kubecost UI that highlights whether or not costs have been already reconciled (although it isn't clear how reliable that functionality is either).

### Solution Description

A simple property in each data element in the return response like `reconciled: True` would be enough. Optionally, it would also be useful to be able to submit this as a query parameter. For example, to only fetch costs that have been reconciled.

### Alternatives

- Fetch data with at least 48 hours of lag: although this should work for the happy path, it's not safe in situations when problems occurred to reconcile the data.
- Test for `*CostAdjustment` properties being different than 0: although true for most cases, there's likely a variety of scenarios where the adjustment for a reconciled cost might still be 0.

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/ISSUE_GUIDELINES.md) and this is a feature request only for the Helm chart.
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by chipzoller** [comment]
Not a Helm chart issue. Transferred to the features-bugs repository per the guidelines [here](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/ISSUE_GUIDELINES.md).

**Comment by chipzoller** [comment]
Hello, in an effort to consolidate our bug and feature request tracking, we are deprecating using GitHub to track tickets. If this issue is still outstanding and you have not done so already, please raise a request at https://support.kubecost.com/.
