### ISSUE TITLE
[BUG] Allocation Report run rate cost is incorrect when schedule sent as csv or pdf to emails 

### ISSUE THREAD

**Issue by briankscheong** [kubecost/features-bugs#44]
### Kubecost Helm Chart Version

1.106.2

### Kubernetes Version

1.23.17

### Kubernetes Platform

EKS

### Description

After setting up the `monthly` run rate allocation report with time window `last week`, downloading the report as pdf (and scheduling it to be sent to email recipients) shows the `cumulative cost` for `last week` instead. The allocation report is correct through the UI, but not when exported as a pdf file (and when it is sent as a scheduled email).

### Steps to reproduce

1. Create a new allocation report with `Last Week` as date option, aggregated by `Namespace`, `Cost` for chart, and `Monthly Rate` for cost metric.
2. Download the file as a PDF (or schedule the report to be sent to an email).

### Expected behavior

An allocation report with a `monthly` run rate based on cost from `last week` should be generated with the correct numbers. If scheduled a report to be sent via email, the same allocation report should be generated.

**Comment by chipzoller** [comment]
Not a Helm chart issue. Transferred to the features-bugs repository per the guidelines [here](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/ISSUE_GUIDELINES.md).

**Comment by briankscheong** [comment]
@chipzoller Thank you! I wanted to note that this issue also happens to the CSV file when being sent as an email.

**Comment by jessegoodier** [comment]
@Briann-CKS 
We have reproduced this issue and are working on a fix. It will likely be in v2.2, but we will let you know if it is sooner.

**Comment by dwbrown2** [comment]
Fix now merged for this, @teevans thinking this will go out in a 2.1.x patch?

**Comment by chipzoller** [comment]
Hello, in an effort to consolidate our bug and feature request tracking, we are deprecating using GitHub to track tickets. If this issue is still outstanding and you have not done so already, please raise a request at https://support.kubecost.com/.
