### ISSUE TITLE
[Bug] Network cost query label

### ISSUE THREAD

**Issue by KKHYeon** [kubecost/features-bugs#45]
### Kubecost Helm Chart Version

1.108.1

### Kubernetes Version

1.28

### Kubernetes Platform

EKS

### Description

In the Cost Analyzer pod, when querying related to network costs, it uses the ‘sameRegion/sameZone’ label for the query. However, the actual metrics collected are set and collected as ‘same_region/same_zone’. 
This could potentially lead to discrepancies or issues due to the difference in label naming conventions used in querying and data collection.

### Steps to reproduce

1.  in cost-analyzer pod log
```
sum(increase(kubecost_pod_network_egress_bytes_total{internet="false", sameZone="false", sameRegion="false", cluster="..."}[2m] )) by (namespace,pod_name,cluster) / 1024 / 1024 / 1024
```
2. network costs actual metrics
```
kubecost_pod_network_egress_bytes_total{pod_name="...",namespace="kube-system",internet="true",same_region="false",same_zone="false",service=""}
```

### Expected behavior

Cost Analyzer pod should use the same labels.

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/ISSUE_GUIDELINES.md) and this is a bug impacting only the Helm chart.
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by chipzoller** [comment]
@thomasvn, is this a Helm issue or something else?

**Comment by thomasvn** [comment]
@KKHYeon @chipzoller Thanks for pointing out the issue! This seems to be a bug in the `cost-model` logic, as opposed to the Helm chart.

**Comment by chipzoller** [comment]
Thanks, Thomas. Transferred to the features-bugs repository.

**Comment by thomasvn** [comment]
This is one location in the code, that matches the incorrect labels you point out. However, `git blame` shows that these lines haven't been modified in ~8months. It's possible that these labels changed when network-costs moved from a Go based image, to a Rust based image. cc @mbolt35 

https://github.com/opencost/opencost/blob/9b43b493563e1b87f023b22fdf2fbe0ae25e06c2/pkg/costmodel/costmodel.go#L236-L238

**Comment by KKHYeon** [comment]
```
# cost-model container log
Query: 'avg(kube_persistentvolumeclaim_info{volumename != "", }) by (persistentvolumeclaim, storageclass, volumename, namespace, cluster_id)[1h:5m]

# values.yaml
kubecostModel:
  promClusterIDLabel: "cluster"
```
And similarly, when querying, use the 'cluster_id' instead of the value set in `promClusterIDLabel` in the query. Thank you for your response.

**Comment by KKHYeon** [comment]
Thank you for your response!

**Comment by mbolt35** [comment]
This issue seems related to the move to rust. The rust prom metric writer is likely just leveraging the internal struct field names (which use the _ naming... go used the camel casing). 

This is a great catch, and thankfully an easy fix. Thanks for flagging me down @thomasvn - this one is definitely on me!

Also, to be clear, this is what I would consider a major feature breaking bug. I'm going to address this and release 0.17.3 ASAP, likely followed by a helm chart update.

**Comment by mbolt35** [comment]
This should be resolved with: https://github.com/opencost/opencost/pull/2478

**Comment by chipzoller** [comment]
Hello, in an effort to consolidate our bug and feature request tracking, we are deprecating using GitHub to track tickets. If this issue is still outstanding and you have not done so already, please raise a request at https://support.kubecost.com/.
