### ISSUE TITLE
Problems with the classic gui [Bug] 

### ISSUE THREAD

**Issue by ShinHiragy** [kubecost/features-bugs#47]
### Kubecost Version

1.106.7

### Kubernetes Version

1.24

### Kubernetes Platform

EKS

### Description

Good afternoon, ladies and gentlemen.

First of all, I wish you a happy new year and hope that it is a successful one. 

Now let's get to the problem!

It is not possible to pay closer attention to the individual positions with Kubecost when using the Classic GUI.

This is not the end of the world if you have to use the new GUI for these purposes, but it is not very nice to have such limitations in the way. 

### Steps to reproduce

1. Change the GUI of Kubecost to the classic alternative
2. Open the Assets-Section
3. Try to open a single value

### Expected behavior

It should show me the values, which it didn`t do currently

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/features-bugs/blob/main/ISSUE_GUIDELINES.md) and this is a bug impacting only the Kubecost application.
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by chipzoller** [comment]
Hello, in an effort to consolidate our bug and feature request tracking, we are deprecating using GitHub to track tickets. If this issue is still outstanding and you have not done so already, please raise a request at https://support.kubecost.com/.
