### ISSUE TITLE
[Bug] Error ingesting data from AWS Billing

### ISSUE THREAD

**Issue by brunopadz** [kubecost/features-bugs#48]
### Kubecost Version

1.106.7 (7d26c3c)

### Kubernetes Version

1.28

### Kubernetes Platform

EKS

### Description

I configured Kubecost to ingest data from AWS Billing using CUR and following the steps described [here](https://docs.kubecost.com/install-and-configure/install/cloud-integration/aws-cloud-integrations).

After the initial ingestion, the integration status shows the "Error (missing Data)" message on Cloud Integrations page. 

I've delved into AWS Glue to inspect the record count in the table and it indicates there's indeed data present. However, the queries executed on Athena are not returning any results.

I'm using a multi-account setup, the result is the same when trying to fetch the billing data from one of the accounts.

EDIT:
I'm now seeing a "Query execution error" messages on cost-model container logs. I've already looked into CUR config settings and Resource IDs are enabled as Report Content.

### Steps to reproduce

1. Configure AWS Cloud Integration using multi-account setup
2. Access Kubecost Cloud Integration page

### Expected behavior

Get billing data from AWS 

### Screenshots

![image](https://github.com/kubecost/features-bugs/assets/1850071/c6ef8b05-5808-400e-a2b0-1f1827944910)

### Logs

```
2024-01-30T20:13:40.801137725Z ERR CloudCost[xxx/s3://aws-athena-query-results-xxx]: ingestor: build failed for window [2024-01-29T00:00:00+0000, 2024-02-05T00:00:00+0000): QueryAthenaPaginated: query execution error: no query results available for query 51cf020c-ed53-4bfb-aadd-4eb318feda65
2024-01-30T20:13:40.820818541Z ERR CloudCost[xxx/s3://aws-athena-query-results-xxx]: ingestor: build failed for window [2023-12-26T00:00:00+0000, 2024-01-02T00:00:00+0000): QueryAthenaPaginated: query execution error: no query results available for query e7e5fc33-9676-4c98-b190-e62cc7c9c7ee
```

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/features-bugs/blob/main/ISSUE_GUIDELINES.md) and this is a bug impacting only the Kubecost application.
- [X] I have searched other issues in this repository and mine is not recorded.

EDIT: Added logs

**Comment by bluecarpincho** [comment]
Hey @brunopadz, were you able to solve this issue? Im facing the exact same problem.

**Comment by haooliveira84** [comment]
Same here :(
