### ISSUE TITLE
[Feature] Add spend change back to the cloud cost view

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/features-bugs#5]
### Problem Statement

When reviewing cloud costs, it's really helpful to see spend change over time, which we used to show on the cloud costs view. 

### Solution Description

Add spend change pills as shown in allocation view

<img width="152" alt="image" src="https://github.com/kubecost/features-bugs/assets/298359/f6897275-2d37-4c9b-8834-f2bb9eda8be3">

### Alternatives

None yet

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/features-bugs/blob/main/ISSUE_GUIDELINES.md) and this is a feature request only for the Kubecost application.
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by teevans** [comment]
Jira: https://kubecost.atlassian.net/browse/SELFHOST-832

**Comment by chipzoller** [comment]
Hello, in an effort to consolidate our bug and feature request tracking, we are deprecating using GitHub to track tickets. If this issue is still outstanding and you have not done so already, please raise a request at https://support.kubecost.com/.
