### ISSUE TITLE
[Feature] Please update AWS EKS add-on to support kubernetes 1.28+

### ISSUE THREAD

**Issue by rbudiharso** [kubecost/features-bugs#51]
### Problem Statement

The AWS EKS add-on for kubecost only support kubernetes version up to 1.27, in the mean time AWS EKS already support k8s 1.28 and 1.29. Please add support for 1.28+

### Solution Description

Add support for k8s 1.28+ on AWS EKS add-on

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/features-bugs/blob/main/ISSUE_GUIDELINES.md) and this is a feature request only for the Kubecost application.
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by jessegoodier** [comment]
@chipzoller, is this something you can look at?

**Comment by chipzoller** [comment]
Sent https://github.com/aws-samples/eks-anywhere-addons/pull/208 to bump the add-on to v2.0.2.

**Comment by chipzoller** [comment]
2.0.2 should now be available.
