### ISSUE TITLE
Addition of shared labels and shared label values

### ISSUE THREAD

**Issue by ShinHiragy** [kubecost/features-bugs#52]
Good morning, everybody.

I have a small question, and I hope that you can give me a helpful answer.

Is it possible to add this values through the use of the values.yaml-file?

- shared Labels
- shared label values

It is part of the shared cost section in the settings-area

**Comment by chipzoller** [comment]
~There is a `global` section allowing you to add both labels and annotations if that's what you mean.~

I see you mean "Shared Labels" in the UI under "Shared Costs". The `kubecostProductConfigs` map has a key for `sharedNamespaces` but not `sharedLabels`. @thomasvn, do you know if this exists via another setting in the chart? If not, may be a good feature request.

**Comment by thomasvn** [comment]
Correct I think we would need a feature request for this.

The UI supports setting "Shared Labels" and "Shared Label Values", however it's not configurable via Helm chart. Only the following are currently configurable:

```yaml
kubecostProductConfigs:
  sharedNamespaces: ""
  sharedOverhead: ""
  shareTenancyCosts: true
```

**Comment by dwbrown2** [comment]
@ShinHiragy is this a feature request you'd like us to review in an upcoming build? Would it be helpful to review any other requirements you have together (related to this feature or others)?

**Comment by chipzoller** [comment]
Transferred to features-bugs repo.

**Comment by ShinHiragy** [comment]
@dwbrown2 Sorry, for the late response. My availability was in the last time not the best :)

Keep it short and simple. Yes, it would be perfect, if it is possible to add this aspect to the helm chart.

**Comment by chipzoller** [comment]
Hello, in an effort to consolidate our bug and feature request tracking, we are deprecating using GitHub to track tickets. If this issue is still outstanding and you have not done so already, please raise a request at https://support.kubecost.com/.
