### ISSUE TITLE
[Bug] Network costs crashing on node startup

### ISSUE THREAD

**Issue by elcomtik** [kubecost/features-bugs#56]
### Kubecost Version

2.0.2

### Kubernetes Version

1.28

### Kubernetes Platform

EKS

### Description

I updated from kubecost v1.105.1 to v1.106.7 and later to v2.0.2

Network costs were updated from v0.6.7 to v0.7.2 and problems started when the new k8s node was created. 

I use standard AL2 EKS nodes, it worked before the update. It seems that the downgrade of network-costs container fixed the issue temporarily.

### Steps to reproduce

When a new k8s node is created Daemonset starts the network-costs pod on the new node and the following error occurs on pod:

```
ERROR kube_client::client::builder: failed with error error trying to connect: deadline has elapsed
ERROR kube_client::client::builder: failed with error error trying to connect: deadline has elapsed
ERROR kube_client::client::builder: failed with error error trying to connect: deadline has elapsed
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: HyperError(hyper::Error(Connect, Custom { kind: TimedOut, error: Elapsed(()) }))', src/kube/netmap.rs:570:44 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: HyperError(hyper::Error(Connect, Custom { kind: TimedOut, error: Elapsed(()) }))', src/kube/netmap.rs:619:45
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: HyperError(hyper::Error(Connect, Custom { kind: TimedOut, error: Elapsed(()) }))', src/kube/netmap.rs:663:47
```

The pod is not emitting any metrics and also not restarted automatically. 

If I restart it manually, it starts working as expected.

### Expected behavior

Network costs start without panicking, or getting restarted by the liveness probe.

### Impact

Network cost metrics are not complete.

### Logs

```Shell
ERROR kube_client::client::builder: failed with error error trying to connect: deadline has elapsed
ERROR kube_client::client::builder: failed with error error trying to connect: deadline has elapsed
ERROR kube_client::client::builder: failed with error error trying to connect: deadline has elapsed
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: HyperError(hyper::Error(Connect, Custom { kind: TimedOut, error: Elapsed(()) }))', src/kube/netmap.rs:570:44 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: HyperError(hyper::Error(Connect, Custom { kind: TimedOut, error: Elapsed(()) }))', src/kube/netmap.rs:619:45
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: HyperError(hyper::Error(Connect, Custom { kind: TimedOut, error: Elapsed(()) }))', src/kube/netmap.rs:663:47
```

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/features-bugs/blob/main/ISSUE_GUIDELINES.md) and this is a bug impacting only the Kubecost application.
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by AjayTripathy** [comment]
cc @mbolt35 is this a timeout contacting the k8s apiserver?

**Comment by AjayTripathy** [comment]
Hi @elcomtik we're pretty sure that this is an intermittent timeout contacting the API server on pod startup, which is why the restart/rollback appears to fix. Could you try again and see if the behavior is the same?

**Comment by elcomtik** [comment]
What version should I test?

**Comment by AjayTripathy** [comment]
v0.17.3

**Comment by zumic96** [comment]
I have added startupProbe and livenessProbe to DaemonSet to go around this issue, strangely I thought they were there by default.
```
livenessProbe:
  tcpSocket:
    port: 3001
  initialDelaySeconds: 5
  timeoutSeconds: 1
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 5
startupProbe:
  tcpSocket:
    port: 3001
  initialDelaySeconds: 5
  timeoutSeconds: 1
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 5
```

**Comment by elcomtik** [comment]
just tested v0.17.3, works good. This issue can be closed.

Thanks a lot!

**Comment by elcomtik** [comment]
I have to admit, I made premature conclusions. Still the same issue.

**Comment by elcomtik** [comment]
@zumic96 adding probes works for me too

**Comment by chipzoller** [comment]
Hello, in an effort to consolidate our bug and feature request tracking, we are deprecating using GitHub to track tickets. If this issue is still outstanding and you have not done so already, please raise a request at https://support.kubecost.com/.
