### ISSUE TITLE
[Bug] History appears to be broken on cloud costs view

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/features-bugs#6]
### Kubecost Version

106.2

### Kubernetes Version

n/a

### Kubernetes Platform

EKS

### Description

Back button in browser stopped working. 

### Steps to reproduce

1. Load this view https://infra.kceng.dev/cloud?reportTitle=Cumulative+cost+for+last+60+days+by+item&window=60d&agg=item&context=W3sicHJvcGVydHkiOiJzZXJ2aWNlIiwidmFsdWUiOiJBbWF6b25FQzIiLCJuYW1lIjoiU2VydmljZSJ9XQ%3D%3D&filters=W10%3D&costMetric=AmortizedNetCost&selectedProviderId=&selectedItemName=
2. Click "Cloud Costs" in navigation
3. Hit back button in your browser

### Expected behavior

Return to the previous view of cloud data.

### Impact

Instead of expected behavior the back button did not change the page. This makes browsing data hard in this particular moment but also causes me to lose some faith in the Kubecost product because most users will view this as table stakes. 

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/features-bugs/blob/main/ISSUE_GUIDELINES.md) and this is a bug impacting only the Kubecost application.
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by teevans** [comment]
Copied to Jira: https://kubecost.atlassian.net/browse/SELFHOST-829

**Comment by chipzoller** [comment]
Hello, in an effort to consolidate our bug and feature request tracking, we are deprecating using GitHub to track tickets. If this issue is still outstanding and you have not done so already, please raise a request at https://support.kubecost.com/.
