### ISSUE TITLE
Internal redirect

### ISSUE THREAD

**Issue by ShinHiragy** [kubecost/features-bugs#62]
Good morning, good midday or good evening. 

I am currently working on an implementation of the EntraID-Service to use it as an OIDC-Provider for the kubecost-application. This part is currently working perfectly fine and doesn`t cause any type of problems. 

Now, it comes to the problem!

The activation of RBAC cause an internal redirect, which makes it impossible to use that feature! I followed the documentation of the kubecost-application and implemented the required configuration values.

I hope, that you can help me in this case to find an perfect solution for the problem.  

Here is the code-snippet:
```
oidc:{
    enabled: true,
    useIDtoken: true,
    clientID: this.options.clientID,
    secretName: this.options.secretName,
    authURL:pulumi.interpolate"https://login.microsoftonline.com/${this.options.tenantID}/oauth2/v2.0/authorize?client_id=${this.options.clientID}&response_type=code&scope=openid&nonce=123456&redirect_uri=https%3A%2F%2F${this.options.hosts}/model/oidc/authorize",
    loginRedirectURL: pulumi.interpolate"https://${this.options.hosts}/model/oidc/authorize",
    discoveryURL: pulumi.interpolate"https://login.microsoftonline.com/${this.options.tenantID}/v2.0/.well-known/openid-configuration",
    skipOnlineTokenValidation: true
    rbac: {
        enabled: true,
        groups: [
        {
            name: "blablaAdministration",
            enabled: true,
            claimName: "roles",
            claimValues: [
                "blablablaAdministration"
            ]
        },
        {
            name: "blablablaRead",
            enabled: true,
            claimName: "roles",
            claimValues: [
                "blablablaRead"
           ]
        }
      ]
    }
}
```

I changed a little bit of the code to make possible, that the code-viewer of gitlab can be used

**Comment by ShinHiragy** [comment]
@chipzoller Sorry, for my mistake and thank you very much for the transfer to the correct area

Maybe, i should start using an pair of glasses for my eyes 😅

**Comment by ShinHiragy** [comment]
Good morning, everybody. 

I changed a few values and checked my entraID-configuration. Now, it is saying, that the auhorization code is already redeemed and the OIDC token request result in an empty token.

I hope, that this new information is helping you

```
2024-03-06T08:12:10.767990158Z INF Token Response: {"error":"invalid_grant","error_description":"AADSTS54005: OAuth2 Authorization code was already redeemed, please retry with a new valid code or use an existing refresh token. Trace ID: 3ffc1f36-b363-4d02-822f-b08f5068c301 Correlation ID: 67b2d8d6-3748-4612-8e7a-e6b1732f2df1 Timestamp: 2024-03-06 08:12:10Z","error_codes":[54005],"timestamp":"2024-03-06 08:12:10Z","trace_id":"3ffc1f36-b363-4d02-822f-b08f5068c301","correlation_id":"67b2d8d6-3748-4612-8e7a-e6b1732f2df1"}
2024-03-06T08:12:10.768055179Z INF Error in OIDC token request: empty token

```

**Comment by AjayTripathy** [comment]
Hi @ShinHiragy, we don't support RBAC at the free tier: https://www.kubecost.com/pricing

If you have an enterprise key or are interested please reach out to team@kubecost.com or support@kubecost.com ... thanks
