### ISSUE TITLE
[Feature] Support Split Cost Allocation Data for Amazon EKS

### ISSUE THREAD

**Issue by z0rc** [kubecost/features-bugs#65]
### Problem Statement

AWS launched new feature for CUR that enables granular cost visibility on container level. See https://aws.amazon.com/about-aws/whats-new/2024/04/aws-split-cost-allocation-data-amazon-eks/ and https://docs.aws.amazon.com/cur/latest/userguide/split-cost-allocation-data.html.

Most likely it's valuable for Kubecost with cost validation and correction. Or maybe some computations can be skipped, if CUR provides resulting values now.

### Solution Description

Up to you how Split Cost Allocation can be integrated into Kubecost.

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/features-bugs/blob/main/ISSUE_GUIDELINES.md) and this is a feature request only for the Kubecost application.
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by chipzoller** [comment]
Hello, in an effort to consolidate our bug and feature request tracking, we are deprecating using GitHub to track tickets. If this issue is still outstanding and you have not done so already, please raise a request at https://support.kubecost.com/.
