### ISSUE TITLE
[Bug] Agrregation by labels (team, department) error in v2.2.2 https://demo.kubecost.xyz/allocations?agg=team

### ISSUE THREAD

**Issue by katerynabay** [kubecost/features-bugs#66]
### Kubecost Helm Chart Version

2.2.2

### Kubernetes Version

1.26

### Kubernetes Platform

EKS

### Description

Arggregation by any label failing with 500. 
![image](https://github.com/kubecost/cost-analyzer-helm-chart/assets/166798145/0093d566-3dbb-4b8a-9390-865a0f37ed5a)

URL: https://demo.kubecost.xyz/allocations?agg=team

{
    "code": 500,
    "data": null,
    "message": "error querying DB: error querying via querysvc query Failure: Parser Error: syntax error at or near \"(\"\nLINE 1: ...T 25) UNION ALL (SELECT '__idle__' AS  (CASE \tWHEN \"container_1d_idle_weighted_...\n                                                  ^"
}

Issue also exist in 2.2.1
Version 2.1.1 works as expected

### Steps to reproduce

1. Monitor -> allocations -> single aggregation (select team)

### Expected behavior

Returned aggregation data

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/ISSUE_GUIDELINES.md) and this is a bug impacting only the Helm chart.
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by teevans** [comment]
@cliffcolvin can you triage? cc @AjayTripathy since you're on support as well

**Comment by chipzoller** [comment]
Not a Helm chart issue. Transferred to features-bugs.

**Comment by cliffcolvin** [comment]
@katerynabay the resolution for this should be in 2.2.3 coming early this week.

**Comment by jiananyim** [comment]
Hello, we are using kubecost 2.2.3 will our mirror images which still have this issue. Could you let us know which image the fix is in?

my mirror image based versions - 
kubecostFrontend:
frontend:prod-2.2.3
kubecostAggregator:
cost-model:prod-2.2.3
kubecostModel:
cost-model:prod-2.2.3
forecasting:
kubecost-modeling:prod-v0.1.3
prometheus
prod-v0.71.2

@cliffcolvin

**Comment by cliffcolvin** [comment]
@jiananyim cost-model should have the fix. Are you saying you are still getting the error? If so can you give me the url to the api that you're using that gets the error so I can look at the label?

**Comment by jiananyim** [comment]
I am calling - 
` http://my_elb_endpoint:9090/model/allocation?window=2024-05-10T00:00:00Z,2024-05-20T00:00:00Z&aggregate=service&shareIdle=false&shareNamespaces=kube-system&sharedSplit=weighted&etl=true`

**Comment by jiananyim** [comment]
I fixed the issue by upgrading to cost-model:prod-2.2.5. 
prod-2.2.3 doesn't work for me (platform linux/amd64)

**Comment by chipzoller** [comment]
Hello, in an effort to consolidate our bug and feature request tracking, we are deprecating using GitHub to track tickets. If this issue is still outstanding and you have not done so already, please raise a request at https://support.kubecost.com/.
