### ISSUE TITLE
[Bug] Cloud cost view not default sorted by total cost

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/features-bugs#7]
### Kubecost Version

106.2

### Kubernetes Version

n/a

### Kubernetes Platform

EKS

### Description

Most other Kubecost views are sorted by total costs, but this particular view of cloud costs is not. 

### Steps to reproduce

1. View this page and look at total cost: https://infra.kceng.dev/cloud?reportTitle=Cumulative+cost+for+last+60+days+by+item&window=60d&agg=item&context=W3sicHJvcGVydHkiOiJzZXJ2aWNlIiwidmFsdWUiOiJBbWF6b25FQzIiLCJuYW1lIjoiU2VydmljZSJ9XQ%3D%3D&filters=W10%3D&costMetric=AmortizedNetCost&selectedProviderId=&selectedItemName=

OR 

1. Visit https://infra.kceng.dev/cloud
2. Drill into EC2 and view this page: https://infra.kceng.dev/cloud?reportTitle=Cumulative+cost+for+last+7+days+by+item&agg=item&context=W3sicHJvcGVydHkiOiJzZXJ2aWNlIiwidmFsdWUiOiJBbWF6b25FQzIiLCJuYW1lIjoiU2VydmljZSJ9XQ%3D%3D&filters=W10%3D

### Expected behavior

Individual items sorted by descending cost. 

### Impact

Was confused how "costs could be $4k+ but then have the biggest item be $6" then saw that there were bigger items in the graph tool tip... thought there was a major data problem... and then realized that data wasn't sorted like in other views. 

### Screenshots

<img width="1933" alt="image" src="https://github.com/kubecost/features-bugs/assets/298359/8edda4dc-6161-47d7-a0f7-059b4aec5f36">

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/features-bugs/blob/main/ISSUE_GUIDELINES.md) and this is a bug impacting only the Kubecost application.
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by teevans** [comment]
Jira:https://kubecost.atlassian.net/browse/SELFHOST-831

**Comment by dwbrown2** [comment]
@teevans I believe now fixed, let me know if more is needed!

**Comment by chipzoller** [comment]
Hello, in an effort to consolidate our bug and feature request tracking, we are deprecating using GitHub to track tickets. If this issue is still outstanding and you have not done so already, please raise a request at https://support.kubecost.com/.
