### ISSUE TITLE
[Feature] Show more decimals in cloud costs graph tooltips

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/features-bugs#8]
### Problem Statement

When looking at daily/hourly trends over time, I'm unable to get a sense for movement by looking at the graph tooltip. 

![image](https://github.com/kubecost/features-bugs/assets/298359/52fce5dd-e8ff-462e-8c06-e612ccd07dd2)

### Solution Description

It would be helpful to show at least one more decimal place, i.e. $2k --> $2.1k

### Alternatives

Show two more decimal places...

### Additional Context

This same concept may apply to others graphs...

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/features-bugs/blob/main/ISSUE_GUIDELINES.md) and this is a feature request only for the Kubecost application.
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by teevans** [comment]
Jira: https://kubecost.atlassian.net/browse/SELFHOST-830

**Comment by chipzoller** [comment]
Hello, in an effort to consolidate our bug and feature request tracking, we are deprecating using GitHub to track tickets. If this issue is still outstanding and you have not done so already, please raise a request at https://support.kubecost.com/.
