### ISSUE TITLE
Showcasing system namespaces in the dashboard separately and flag in Allocation API

### ISSUE THREAD

**Issue by passionInfinite** [kubecost/features-bugs#80]
**What problem are you trying to solve?**
We have some tenants which share the same cluster and we would like a flexibility to standout the system namespace (maybe different color text or label) this will help the cluster tenants to get to know that system namespace cost will be shared with other tenants.

**Describe the solution you'd like**
Currently, kubecost doesn't show system namespaces (in different color) or some kind of flag that can show which namespaces are system namespaces. To give the flexibility to know teams which are the namespaces for which the cost will be shared with other tenants in the same cluster. Also, if we have a flag in the Allocation API that shows that namespace is a system namespace in API response that will help us for the automation.

**Describe alternatives you've considered**

**How would users interact with this feature?**
1. Users will be seeing the system namespace cost separately in the UI.
2. Users will be able to filter the cost in allocations only for system namespace.
3. Users will be able to use the Allocation API to automate the chargeback process based on the system namespaces.

**Comment by mmurph3** [comment]
cc @kwombach12

**Comment by mmurph3** [comment]
@passionInfinite I know there are default ones like kube-system, default, kube-public, kube-node-lease, etc. I recall there was mention of others like istio and more. Are these custom images you're using or custom cluster configurations that are outside of the norm?

**Comment by kwombach12** [comment]
Users can add these system namespaces as shared namespaces so that their costs are proportionally distributed to the other allocations and used in chargeback. Are there other use cases you see here? @passionInfinite

**Comment by passionInfinite** [comment]
The problem that I see, is we will need to maintain the list of the namespaces which are system namespaces, why not we make it use of a reserved label so that kubecost can use that label to show it differently that way Teams who are looking at items in the dashboard gets to know that cost of that specific resource is shared because it is a system resource. Also, in the  shared namespaces we can then simply pass the reserved label and under the hood it can get the list and share the cost as it shares the cost right now. 

This will completely get rid of maintaining list of namespaces which is not at all user friendly. Also Kubecost will be able to show those resources as System Resources (Separately) in the Allocations Dashboard. In API we can similarly leverage the use of those labels to do further automation.

**Comment by kwombach12** [comment]
Thanks @passionInfinite for that explanation. We will consider this for a future release

**Comment by chipzoller** [comment]
Closing stale request.
