### ISSUE TITLE
Testing Slack alerts should include some payload

### ISSUE THREAD

**Issue by ivankube** [kubecost/features-bugs#82]
**Describe the bug**  
Slack integration for Recurring updates is not working.

**To Reproduce**  

1. Create new Recurring Updated alert with Slack web hook
2. Click "Test Alert"
3. Receive [null payload](https://webhook.site/#!/6477c4f5-bd9e-4d41-aafd-c440daa73400/0daa980e-48d0-4f32-bf74-73b191e24ecc/1)

**Expected behavior**  
Slack alert for Recurring Update should work.

**Please share the support case, if any**  
https://kubecost.zendesk.com/agent/tickets/4096

**Comment by kwombach12** [comment]
@ivankube This is WAI for me. I get a test alert with the window, aggregation, and filters. 
<img width="561" alt="Screenshot 2023-06-28 at 2 25 17 PM" src="https://github.com/kubecost/cost-analyzer-helm-chart/assets/86785820/5e45de44-68b8-45cc-aea3-009b205bba3a">

**Comment by ivankube** [comment]
@kwombach12 I believe we are missing data in this test alert.

For example, if I follow the same steps for Allocation budget alert, I [receive](https://webhook.site/#!/6477c4f5-bd9e-4d41-aafd-c440daa73400/e2775241-5df7-4d04-aa14-b00bc62627ad/1):

{
  "text": "***This is a test Kubecost Budget Alert. No budgets have actually been exceeded.***\nYou are receiving this alert because a set budget of USD100.00 has been exceeded.\n\n*Cluster Name:* kc-demo-prod\n```\n       Namespace                            nginx-ingress\n       Cost                                     USD150.00\n       % Overage                                    50.0%\n       Namespace                                 miketest\n       Cost                                     USD150.00\n       % Overage                                    50.0%\n       Namespace                           netapp-ingress\n       Cost                                     USD150.00\n       % Overage                                    50.0%\n       Namespace                            __unmounted__\n       Cost                                     USD150.00\n       % Overage                                    50.0%\n       Namespace                                 aks-app1\n       Cost                                     USD150.00\n       % Overage                                    50.0%\n       Namespace                                 qa-stage\n       Cost                                     USD150.00\n       % Overage                                    50.0%\n       Namespace                              staging-app\n       Cost                                     USD150.00\n       % Overage                                    50.0%\n       Namespace                     kubernetes-dashboard\n       Cost                                     USD150.00\n       % Overage                                    50.0%\n       Namespace                             cert-manager\n       Cost                                     USD150.00\n       % Overage                                    50.0%\n       Namespace                               audit-demo\n       Cost                                     USD150.00\n       % Overage                                    50.0%\n       Namespace                           kubecost-cloud\n       Cost                                     USD150.00\n       % Overage                                    50.0%\n       Namespace                                  qa-prod\n       Cost                                     USD150.00\n       % Overage                                    50.0%\n       Namespace                                   qa-dev\n       Cost                                     USD150.00\n       % Overage                                    50.0%\n       Namespace                                 kubecost\n       Cost                                     USD150.00\n       % Overage                                    50.0%\n       Namespace                                 demo-app\n       Cost                                     USD150.00\n       % Overage                                    50.0%\n       Namespace                                   pacman\n       Cost                                     USD150.00\n       % Overage                                    50.0%\n       Namespace                                   thanos\n       Cost                                     USD150.00\n       % Overage                                    50.0%\n       Namespace                           infra-kubecost\n       Cost                                     USD150.00\n       % Overage                                    50.0%\n       Namespace                                 opencost\n       Cost                                     USD150.00\n       % Overage                                    50.0%\n       Namespace                                  default\n       Cost                                     USD150.00\n       % Overage                                    50.0%\n       Namespace                                  grafana\n       Cost                                     USD150.00\n       % Overage                                    50.0%\n       Namespace                              kube-system\n       Cost                                     USD150.00\n       % Overage                                    50.0%\n       Namespace                             acme-fitness\n       Cost                                     USD150.00\n       % Overage                                    50.0%\n       Namespace                      netapp-loadbalancer\n       Cost                                     USD150.00\n       % Overage                                    50.0%\n       Namespace                            ingress-nginx\n       Cost                                     USD150.00\n       % Overage                                    50.0%\n       Namespace                              nginx-mikem\n       Cost                                     USD150.00\n       % Overage                                    50.0%\n       Namespace                               monitoring\n       Cost                                     USD150.00\n       % Overage                                    50.0%\n```\n"
}

**Comment by kwombach12** [comment]
@ivankube I believe that recurring alerts simply dont send data today when users send a test. @cliffcolvin please correct me if I'm wrong. I think it makes sense to send some data in the test message, and so I would consider this a feature request we can look to pickup in a future release

**Comment by pjaak** [comment]
+1 to having this as a feature request, would be really useful for us to see data when we send the test alert to slack

**Comment by chipzoller** [comment]
Hello, in an effort to consolidate our bug and feature request tracking, we are deprecating using GitHub to track tickets. If this issue is still outstanding and you have not done so already, please raise a request at https://support.kubecost.com/.
