### ISSUE TITLE
[Feature] Enable Highlight Unreconciled Costs in Helm chart

### ISSUE THREAD

**Issue by andy-neara** [kubecost/features-bugs#87]
### Problem Statement

Unreconciled costs can be ways off from the reconciled value so it's important that it is highlighted to ensure data is not misinterpreted by uninformed Kubecost users. 

### Solution Description

Expose Highlight Unreconciled Costs via the Helm chart so that it can be enabled by default for every Kubecost user.

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/ISSUE_GUIDELINES.md) and this is a feature request only for the Helm chart.
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by chipzoller** [comment]
Transferred to features-bugs. This needs to be a configurable option in the first place and afterwards exposed via a Helm flag. So it's not just a matter of changing the chart.

**Comment by chipzoller** [comment]
Hello, in an effort to consolidate our bug and feature request tracking, we are deprecating using GitHub to track tickets. If this issue is still outstanding and you have not done so already, please raise a request at https://support.kubecost.com/.
