### ISSUE TITLE
Link to "Inspect Details" for any aggregation group (Owner/Product etc), fix missing Cloud/Network

### ISSUE THREAD

**Issue by kc-adawson** [kubecost/features-bugs#9]
**What problem are you trying to solve?**

In /allocations in the UI, users are able to "Inspect Details" when aggregating by Namespace. This opens the /details page in a new browser tab. This is shown as an option when aggregating by namespace, but not when aggregating from a group like "Owner" or "Product"

[Examples of the "Inspect Details" pop-up for aggregation:namespace]

![](https://user-images.githubusercontent.com/101200254/214426874-4382e9ef-51d3-4aa8-bf1a-b648d6e1a80a.png)

You are able to edit the endpoint URL directly and specify the name + type (shown below), and it brings up the /details page for that selection. In my case, I will use "type=product,name=grafana", which works but this /details page is missing the "Cloud Costs" and "Network Costs".

![](https://user-images.githubusercontent.com/101200254/214433263-0b3e1c7c-cc66-49ed-9e9e-9d3c837b5f22.png)

If I go to Advanced Reporting, I can see the "product:grafana" line item does have associated external cost, so it should also show within the /details inspector page.

![](https://user-images.githubusercontent.com/101200254/214433531-9015b15d-9b53-49b9-b1f8-186c91319591.png)

[Example of a different /details page for "namespace:kubecost" - this one showing the Cloud + Network Costs]

![](https://user-images.githubusercontent.com/101200254/214431414-0f8fed83-7381-4981-828e-b53e7dbc8cff.png)

**Describe the solution you'd like**

Add ability to pull up the Inspect Details (<kubecost-url>/details) for any aggregation in the UI. This would behave just like it does in v1.99 /allocations UI for "namespace"

Within each new /details page, add Cloud Costs and Network Costs that are currently missing when you go to the URL directly.

This should ideally be added to Advanced Reporting as well. I should be able to click and get to the "Inspect Details" page from any "aggregation" row where possible.

**Describe alternatives you've considered**

If these pages need to be accessed via hard coding the URL vs adding an "Inspect Details" hyperlink to each reporting row in UI, that would be fine, but the cloud costs + network costs that are missing when going direct to the URL should be added

**How would users interact with this feature?**

They would click on the row name within the UI and "Inspect Details" when aggregating by Owner/Team/Department/Environment (any of the built-in "aggregation groups"). This would be an option in any reporting view that makes sense, including in the new Advanced Reporting.

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-17) by [Unito](https://www.unito.io)

**Comment by kwombach12** [comment]
@kc-adawson Thanks for adding this. I will log a ticket with the team for adding the Cloud/Network Costs to other /details pages.

In terms of /details pages for other aggregations, I agree that we should add that functionality for aggregations like "Owner" (I am seeing /details page for "Product" today). Additionally, we are working on a /details page for "Cluster" in 1.101. (the clusters' details page will look very different than the existing /details pages). What other aggregations do you think should have a /details page? I'm not sure that the existing page makes sense for "Node" aggregation and I wonder how useful it is when aggregating by "pods"

**Comment by dwbrown2** [comment]
@kc-adawson feel like this is still outstanding? happy to revisit if so.

**Comment by kc-adawson** [comment]
As of the latest 1.106.3 this still happens - The bottom "Alerts/Cloud/Network/" section only shows when "Inspecting" 
by namespace, but does not show when using "Inspect" on any of the built-in label groups in /allocations. (Product, Team, etc)

<img width="1262" alt="2023-10-11_08-15-36" src="https://github.com/kubecost/cost-analyzer-helm-chart/assets/101200254/312e1908-3392-4f4c-9b74-073be7ed6af6">

<img width="1302" alt="2023-10-11_08-15-51" src="https://github.com/kubecost/cost-analyzer-helm-chart/assets/101200254/b1b7c756-fd98-4800-bbb1-87a82786c0a1">

**Comment by chipzoller** [comment]
transferred

**Comment by dwbrown2** [comment]
@nealormsbee pretty quick to support?

**Comment by nealormsbee** [comment]
I'd imagine so -- creating a Jira ticket!

**Comment by nealormsbee** [comment]
On further inspection, there are architectural decisions in the Allocation Details page today that make this not-so-quick. In any case, there's a Jira issue [here](https://kubecost.atlassian.net/jira/polaris/projects/KC/ideas/view/2936873?selectedIssue=KC-128) so we can cycle this in for development in the near future.

**Comment by chipzoller** [comment]
Hello, in an effort to consolidate our bug and feature request tracking, we are deprecating using GitHub to track tickets. If this issue is still outstanding and you have not done so already, please raise a request at https://support.kubecost.com/.
