### ISSUE TITLE
Enhance the Govern (Budget) feature by allowing custom filters and OOC cost within it

### ISSUE THREAD

**Issue by danielpsf** [kubecost/features-bugs#92]
**What problem are you trying to solve?**
Part of enabling the FinOps culture within my company is the usage of Kubecost to set budgets and chargebacks per team. So, the idea is that the visibility for the team is a 360˚ one, starting from their app, which is within Kubernetes, and encapsulating all the adjacent infrastructure within the Cloud provider, therefore, enabling the Govern > Budget feature to have more filter options and also aggregate it with OOC cost would allow me to fulfill all the required requisites for chargeback/budgeting within my company.

**Describe the solution you'd like**
- GIVEN I have a team described by the label `owner`
- WHEN I navigate to Govern > Budget
- AND create a new budget
- THEN I want to be able to filter by label: `owner``
- AND this should filter not only in cluster cost but also OOC cost as well

**Describe alternatives you've considered**
Right now, I have regular Advanced Reports (which have a filter issue, but it is been fixed), and I go through it with all the managers on a bi-weekly basis, which is very inconsistent as managers within the sync-up meeting are focusing on something else rather than checking if they're within their budget or not in a report page that is not super simple.

**How would users interact with this feature?**
- Through a configured budget alert within HELM chart
- Through the UI by creating budgets with more complex filtering

**Comment by thomasvn** [comment]
@danielpsf I like this idea! Currently in v1.104 you can only create a budget for a Namespace or a Cluster. I think as a first step creating a budget using any filter/aggregation (e.g. filter `label:owner`) would be a good feature. Then eventually tying in out-of-cluster costs into the budget feature.

Waiting for further input from @kwombach12 who will be back in ~1week.

**Comment by kwombach12** [comment]
@danielpsf thank you so much for logging this. Adding more filters and non-K8s to the budget page is absolutely in our roadmap. I hope to have some of these enhancements added to the page in the next few releases!

**Comment by chipzoller** [comment]
Appears to be tracked internally as an idea in a combination of KC-9 and KC-154.

**Comment by chipzoller** [comment]
Hello, in an effort to consolidate our bug and feature request tracking, we are deprecating using GitHub to track tickets. If this issue is still outstanding and you have not done so already, please raise a request at https://support.kubecost.com/.
